# Navbar Menus
[[nav]]
  name    = "Accueil"
  url     = "/fr"
  weight  = 1
[[nav]]
  name    = "À propos"
  url     = "/fr/about"
  weight  = 2
[[nav]]
  name    = "Newsroom"
  url     = "/fr/newsroom"
  weight  = 3
[[nav]]
  name   = "Nominer quelqu'un"
  url     = "/fr/nominated"
  weight  = 4