# Navbar Menus
[[nav]]
  name    = "Home"
  url     = "/"
  weight  = 1
[[nav]]
  name    = "About"
  url     = "about"
  weight  = 2
[[nav]]
  name    = "Newsroom"
  url     = "newsroom"
  weight  = 3
# [[nav]]
#   name    = "Vote"
#   url     = "vote"
#   weight  = 4