# Site Params
logo = "images/logo.png"
dateFormat = "26 FEB 1994"
# Meta data
description = "AfricTivistes Civic Action Prize | Prix AfricTivistes pour l'action civique"
author = "AfricTivistes"
# Google Analitycs
googleAnalitycsID = "G-6S69LEB4Q1"

# Navbar Action Button
[navAction]
status  = true
name    = "Nominate Someone"
url     = "contact"
