# Banner Section
[banner]
enable                = true
background_image      = "/images/backgrounds/logoo.png"
heading               = ""
tagline               = ""
primary_button        = "About"
primary_button_url    = "about"
secondary_button      = "Champions"
secondary_button_url  = "vote"

[call_to_action]
enable              = true
background_image    = "images/backgrounds/cta-background.jpg"
title               = "Don’t be shy ! Vote for someone."
primary_button      = "Champions"
primary_button_url  = "vote"

[newsroom]
enable    = true
title     = "NEWSROOM"
subtitle  = "Latest news on AfricTivistes Civic Action Prize."

[press]
enable    = true
title     = "THE MEDIA IS TALKING ABOUT IT"
subtitle  = ""

[comitejury]
enable    = true
title     = "SELECTION COMMITTEE / FINAL JURY"
subtitle  = ""

[footer]
# Footer Contact Info
[footer.contactInfo]
    title = "Contact Information"
    address = "AfricTivistes, BP : 19968 (Sénégal)"
    phone = "(+221) 33 837 51 24"
    email = "info@africtivistes.org"
    # Footer Sitemap
    [footer.sitemap]
    title = "Sitemap"
    [[footer.sitemap.link]]
        name = "Home"
        url = "/"
    [[footer.sitemap.link]]
        name = "About"
        url = "/about"
    [[footer.sitemap.link]]
        name = "Newsroom"
        url = "/newsroom"
    [[footer.sitemap.link]]
        name = "Nominate someone"
        url = "/nominated"
    # Footer Social Media
    [footer.social]
    title = "Social Media"
    [[footer.social.link]]
        name = "Twitter"
        url = "https://twitter.com/AFRICTIVISTES"
    [[footer.social.link]]
        name = "Facebook"
        url = "https://www.facebook.com/africtivistes/"
    # Footer Service
    [footer.service]
    title = "AfricTivists Civic Action Award"
    description = "Rewarding citizen champions"