############################# English ############################
[en]
languageCode  = "en-us"
languageName = "En"
title = "AfricTivistes Civic Action Prize"
contentDir = "content/english"
weight = 1

############################# French ############################
[fr]
languageCode  = "fr"
languageName = "Fr"
title = "Hackathon #Innov4Democracy"
contentDir = "content/french"
weight = 2
    