# Site Params
logo = "images/logo.png"
dateFormat = "26 FEB 1994"
# Meta data
description = "Hackathon : « Innover pour la démocratie et la bonne gouvernance en Afrique » #Innov4Democracy #AfricTivistes"
author = "AfricTivistes"
# Google Analitycs
googleAnalitycsID = "G-6S69LEB4Q1"

# Navbar Action Button
[navAction]
status  = true
name    = "Nominate Someone"
url     = "contact"
