backend:
  name: git-gateway

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"

collections:
  - name: "page_en"
    label: "Page in English"
    files:
      - file: "site/content/english/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Content", name: "body", widget: "markdown"}
  - name: "newsroom_en"
    label: "Newsroom in English"
    folder: "site/content/english/newsroom"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
 